spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: doithanhchung20011110@gmail.com
    password: mkowadspalufexyn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp
  security:
    user:
      name: admin
      password: 123456